/* Full official names of UN-SWAP participating entities.
   Edit freely — keys must match the short names in the ratings Excel.
   Reference: https://gendercoordinationandmainstreaming.unwomen.org/entities/un-swap-participating-entities */
window.ENTITY_NAMES = {
  "CTBTO": "Preparatory Commission for the Comprehensive Nuclear-Test-Ban Treaty Organization",
  "DCO": "Development Coordination Office",
  "DESA": "Department of Economic and Social Affairs",
  "DGACM": "Department for General Assembly and Conference Management",
  "DGC": "Department of Global Communications",
  "DMSPC": "Department of Management Strategy, Policy and Compliance",
  "DOS": "Department of Operational Support",
  "DPO": "Department of Peace Operations",
  "DPPA": "Department of Political and Peacebuilding Affairs",
  "DSS": "Department of Safety and Security",
  "ECA": "Economic Commission for Africa",
  "ECE": "Economic Commission for Europe",
  "ECLAC": "Economic Commission for Latin America and the Caribbean",
  "ESCAP": "Economic and Social Commission for Asia and the Pacific",
  "ESCWA": "Economic and Social Commission for Western Asia",
  "FAO": "Food and Agriculture Organization of the United Nations",
  "IAEA": "International Atomic Energy Agency",
  "ICAO": "International Civil Aviation Organization",
  "IFAD": "International Fund for Agricultural Development",
  "IIIM Syria": "International, Impartial and Independent Mechanism for Syria",
  "ILO": "International Labour Organization",
  "IMO": "International Maritime Organization",
  "IOM": "International Organization for Migration",
  "IRMCT": "International Residual Mechanism for Criminal Tribunals",
  "ITC": "International Trade Centre",
  "ITU": "International Telecommunication Union",
  "OAJ": "Office of Administration of Justice",
  "OCHA": "Office for the Coordination of Humanitarian Affairs",
  "ODA": "Office for Disarmament Affairs",
  "OHCHR": "Office of the United Nations High Commissioner for Human Rights",
  "OHRLLS": "Office of the High Representative for the Least Developed Countries, Landlocked Developing Countries and Small Island Developing States",
  "OIOS": "Office of Internal Oversight Services",
  "OLA": "Office of Legal Affairs",
  "OSAA": "Office of the Special Adviser on Africa",
  "OSRSG-CAAC": "Office of the Special Representative of the Secretary-General for Children and Armed Conflict",
  "OSRSG-SVC": "Office of the Special Representative of the Secretary-General on Sexual Violence in Conflict",
  "OSRSG-VAC": "Office of the Special Representative of the Secretary-General on Violence against Children",
  "Ombudsman": "Office of the United Nations Ombudsman and Mediation Services",
  "UN Global Compact": "United Nations Global Compact",
  "UN Women": "United Nations Entity for Gender Equality and the Empowerment of Women",
  "UN Youth": "United Nations Youth Office",
  "UN-HABITAT": "United Nations Human Settlements Programme",
  "UNCCD": "Secretariat of the United Nations Convention to Combat Desertification",
  "UNCDF": "United Nations Capital Development Fund",
  "UNCTAD": "United Nations Conference on Trade and Development",
  "UNDP": "United Nations Development Programme",
  "UNDRR": "United Nations Office for Disaster Risk Reduction",
  "UNEP": "United Nations Environment Programme",
  "UNESCO": "United Nations Educational, Scientific and Cultural Organization",
  "UNFCCC": "Secretariat of the United Nations Framework Convention on Climate Change",
  "UNFPA": "United Nations Population Fund",
  "UNHCR": "Office of the United Nations High Commissioner for Refugees",
  "UNICC": "United Nations International Computing Centre",
  "UNICEF": "United Nations Children's Fund",
  "UNICRI": "United Nations Interregional Crime and Justice Research Institute",
  "UNIDIR": "United Nations Institute for Disarmament Research",
  "UNIDO": "United Nations Industrial Development Organization",
  "UNITAR": "United Nations Institute for Training and Research",
  "UNOCT": "United Nations Office of Counter-Terrorism",
  "UNODC": "United Nations Office on Drugs and Crime",
  "UNOG": "United Nations Office at Geneva",
  "UNON": "United Nations Office at Nairobi",
  "UNOPS": "United Nations Office for Project Services",
  "UNOV": "United Nations Office at Vienna",
  "UNRISD": "United Nations Research Institute for Social Development",
  "UNRWA": "United Nations Relief and Works Agency for Palestine Refugees in the Near East",
  "UNSSC": "United Nations System Staff College",
  "UNU": "United Nations University",
  "UNV": "United Nations Volunteers programme",
  "UN Tourism": "World Tourism Organization",
  "UPU": "Universal Postal Union",
  "WFP": "World Food Programme",
  "WHO": "World Health Organization",
  "WIPO": "World Intellectual Property Organization",
  "WMO": "World Meteorological Organization"
};
